### ISSUE TITLE
license appropriate?

### ISSUE THREAD

**Issue by lorvent** [CodeToWeb/Laravel-DatatablesEditor#1]
because http://editor.datatables.net/ is not free and they offer 15 day trial
so i am curious

**Comment by kirkpatrick** [comment]
I have received approval from the author of DataTables Editor to post this code. They're software is commercial but this is a separate release for Laravel. I'm not associated with their company. 
The DataTables test module is included for demo purposes. The author has created a custom DataTables Editor test JavaScript module especially for this demo.
I'm new here so please inform me of how this may be inappropriate. Is it not appropriate to create an open source module to a commercial product?

**Comment by lorvent** [comment]
Hi,
if you already got approval from author then its fine

i just want to make sure of that since its a commercial product and as you are not including editor origin code in repo...you should be fine :) :+1:

**Comment by kirkpatrick** [comment]
Thanks for your feedback and reassurance. I do appreciate it.
