### ISSUE TITLE
Not refreshing data after an edit.

### ISSUE THREAD

**Issue by mickby** [CodeToWeb/Laravel-DatatablesEditor#3]
Did you ever have a problem with this?
The edit saves OK and the response is: 
{"data":[{"DT_RowId":"row_37","name":"Bette ZZZZZ"}]}

But the Datatable does not update. 

In your demo (http://datatables.codetoweb.com/demo) it looks like there is a second response;
{"draw":5,"recordsTotal":9,"recordsFilte

Apart from that (which is probably my mistake ) this package is amazing.

**Comment by mickby** [comment]
I think this is because I am trying to use inline editing and  therefore only the edited field is posted. It looks like the whole row needs to be send back, for the grid to refresh.

**Comment by afrakhan123** [comment]
HI please can you tell me if you solved this. The whole row does not come back and I get an error. Only the edited field comes back

**Comment by mickby** [comment]
I stopped using this package and instead used the Datatables PHP Library : 
https://editor.datatables.net/manual/php/
